### ISSUE TITLE
You needn't have the variable assignment or the explicit return

### ISSUE THREAD

**Issue by dummied** [Vocal-TIYApp2016/vocal#188]
https://github.com/Vocal-TIYApp2016/vocal/blob/master/app/controllers/articles_controller.rb#L10-L13

Just

```ruby
current_user.legislators.each.flat_map do |leg|
  Article.search_by_full_text(leg.full_name).to_a
end
```

will suffice

**Comment by ccflack** [comment]
Removed extra assignment lines here and elsewhere.
